### KD树

为了解决效率低下的暴力计算方法，已经发明了大量的基于树的数据结构。总的来说，这些结构试图通过有效地编码样本的 aggregate distance (聚合距离) 信息来减少所需的距离计算量。k-d树是每个节点都为k维点的二叉树。所有非叶子节点可以视作用一个超平面把空间分割成两个半空间。节点左边的子树代表在超平面左边的点，节点右边的子树代表在超平面右边的点。选择超平面的方法如下：每个节点都与k维中垂直于超平面的那一维有关。因此，如果选择按照x轴划分，所有x值小于指定值的节点都会出现在左子树，所有x值大于指定值的节点都会出现在右子树。这样，超平面可以用该x值来确定，其法线为x轴的单位向量

In [1]:
from sklearn.neighbors import KDTree
import numpy as np

X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
kdt = KDTree(X, leaf_size=30, metric='euclidean')
result = kdt.query(X, k=2, return_distance=False)
print(result)

[[0 1]
 [1 0]
 [2 1]
 [3 4]
 [4 3]
 [5 4]]


### Ball树

为了解决 KD 树在高维上效率低下的问题,提出了Ball树. 其中KD树沿笛卡尔轴（即坐标轴）分割数据, Ball树在沿着一系列的hyper-spheres来分割数据。通过这种方法构建的树要比KD树消耗更多的时间, 但是这种数据结构对于高结构化的数据是非常有效的, 即使在高维度上也是一样。
Ball树将数据递归地划分为由质心 C 和半径 R 定义的节点,使得节点中的每个点位于由 r 和 C 定义的 hyper-sphere 内。 通过使用 triangle inequality（三角不等式） 减少近邻搜索的候选点数。

In [2]:
from sklearn.neighbors import BallTree
import numpy as np

rng = np.random.RandomState(0)
X = rng.random_sample((10, 3))
tree = BallTree(X, leaf_size=2)
dist, ind = tree.query(X[:1], k=3)              
print(ind)  # 查询三个最近邻点

print(dist)  # 查询三个最近邻点距离

[[0 3 1]]
[[0.         0.19662693 0.29473397]]
